dataset_args:
  dataset_name: nyc
  min_poi_freq: 9
  min_user_freq: 9
  session_time_interval: 720
  threshold: 0.005
  filter_mode: jaccard
  num_spatial_slots: 3000
  spatial_slot_type: linear
  do_label_encode: True
  only_last_metric: True
  max_d_epsilon: 5
  distance_threshold: 2.5
  distance_type: haversine
  max_seq_len: 100
  eta: 1
  PADDING_IDX: 7129
  NUM_USERS: 1048
  NUM_POIS: 4981
  conv: sym
  batch_size: 100
model_args:
  model_name: My_Exp
  intra_jaccard_threshold: 0.0
  inter_jaccard_threshold: 0.005
  sizes: 300-500
  dropout_rate: 0.1
  num_edge_type: 3
  num_layers: 2
  generate_edge_attr: True
  embed_fusion_type: concat
  embed_size: 128
  st_embed_size: 128
  activation: relu
  phase_factor: 5
  use_linear_trans: True
  do_traj2traj: True
  distance_encoder_type: time
  quantile: 0.85
  region-embed-dim: 128
  hotness-embed-dim: 16
seq_transformer_args:
  sequence_length: 20
  header_num: 2
  encoder_layers_num: 2
  hidden_size: 512
  dropout: 0.3
  do_positional_encoding: True
conv_args:
  num_attention_heads: 4
  residual_beta: 0.5
  learn_beta: false
  conv_dropout_rate: 0.1
  trans_method: add
  edge_fusion_mode: add
  head_fusion_mode: concat
  time_fusion_mode: add
  residual_fusion_mode: add
  negative_slope: 0.2
run_args:
  seed: 80786525
  gpu: 0
  batch_size: 64
  eval_batch_size: 64
  learning_rate: 0.0001
  do_train: True
  do_validate: True
  do_test: True
  warm_up_steps: 8000
  cooldown_rate: 1.5
  max_steps: 100000
  epoch: 20
  valid_steps: 500
  num_workers: 4
  init_checkpoint: